// <auto-generated />
namespace E_LEARNING.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CursoProfeCursos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CursoProfeCursos));
        
        string IMigrationMetadata.Id
        {
            get { return "202004040303035_CursoProfe-Cursos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
